# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.1
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version = 2.11.0
maven_group = com.github.TheRedBrain
archives_base_name = rpg-inventory

# Dependencies
fabric_api_version=0.146.1+26.1.2
fzzy_config_version=0.7.6+26.1
slot_customization_api_version=4.0.1

# Compatibilities
health_regeneration_overhaul_version=4.0.0
inventory_size_attributes_version=3.0.0
stamina_attributes_version=4.0.1
mana_attributes_version=4.0.0
overhauled_damage_version=3.0.0
resource_bar_api_version=4.0.0
backpack_attribute_version=4.0.0
#player_attribute_screen_version=1.1.0
#rpg_crafting_version=1.3.0
#better_combat_extension_version=2.11.0
#spell_engine_extension_version=2.16.0
#combat_roll_version=2.0.1+1.21.1
#numismatic_overhaul_version=0.3.4+1.21
#script_blocks_version=0.0.8
#
#cloth_config_version=15.0.140
#better_combat_version=2.3.2+1.21.1-fabric
#player_animator_version=2.0.1+1.21.1
#spell_engine_version=1.9.9+1.21.1-fabric
#spell_power_version=1.4.6+1.21.1-fabric
#tiny_config_version=3.1.0-fabric
#trinkets_version=3.10.0
#owo_lib_version=0.12.15.4+1.21
